on:
  push:
    branches:
      - master
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # build
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9  # Choose the Python version you need
      - name: Install MkDocs and Dependencies
        run: |
          pip install mkdocs
      - name: Build MkDocs Documentation
        run: |
          mkdocs gh-deploy --force
